Repository mithril-security/bastionlab, pull requests merged in 2022-11, with the labels that each got.

#70 Fix proto gen in setup.py
  client/setup.py
Labels: C-bug, P-high, S-waiting-on-dhalf, A-python-build

#72 [Fix] Formatting
  .github/workflows/formatting.yml
  .pre-commit-config.yaml
  client/setup.py
  install_pre_commit_hook.sh
Labels: C-bug, P-high, A-python-build

#79 Adding README file
  README.md
Labels: P-critical, C-docs, A-general

#80 Adds setting up keys section
  docs/docs/quick-tour/quick-tour.ipynb
Labels: P-critical, C-docs, A-general

#85 Update README.md
  README.md
Labels: P-high, C-docs, A-general

#84 fixes access control and sanitization bugs, bumps to v0.3.2
  client/src/bastionlab/version.py
  docs/docs/quick-tour/quick-tour.ipynb
  server/Cargo.lock
  server/Cargo.toml
  server/src/access_control.rs
  server/src/composite_plan.rs
  server/src/main.rs
  server/src/serialization.rs
  server/src/utils.rs
Labels: A-server, C-bug, P-critical
